server:
  port: 8769
spring:
  application.name: turbine
security.basic.enabled: false
turbine:
  appConfig: client-ribbon,client-feign
  clusterNameExpression: new String("default")
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/