server:
  port: 8783

spring:
  zipkin:
    base-url: http://localhost:8781
    service:
      name: zipkin-client-child #不设置，取spring.application.name值
    compression:
      enabled: true #发送给zipkin之前进行压缩
    locator:
      discovery:
        enabled: true
  sleuth:
    sampler:
      percentage: 1
  application:
    name: client-child

customer:
  url: http://localhost:8782/client/info

