server:
  port: 8760 # 集群二：注册中心占用8760端口
eureka:
  instance:
    hostname: cluster2
  client:
    register-with-eureka: false # 是否将eureka自身作为应用注册到eureka注册中心
    fetch-registry: false # false来表明自己是一个eureka server
    service-url:
      defaultZone: http://cluster1:8761/eureka
