eureka:
  client:
    service-url:
#     defaultZone : http://localhost:8761/eureka,http://localhost:8760/eureka # eureka集群
     defaultZone : http://localhost:8761/eureka
server:
  port: 8762
#spring:
#  application:
#    name: eureka-client-demo #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name

